namespace AutoTyper.DeviceEmulator.Native;

/// <summary>
/// Contains information about a simulated message generated by an input device other than a keyboard or mouse.
/// </summary>
/// <remarks>
/// HARDWAREINPUT structure 
/// Contains information about a simulated message generated by an input device other than a keyboard 
/// or a mouse.  
/// <code>
/// C++
/// typedef struct tagHARDWAREINPUT {
///    DWORD uMsg;
///    WORD wParamL;
///    WORD wParamH;
/// } HARDWAREINPUT, *PHARDWAREINPUT
/// </code>
/// (see: http://msdn.microsoft.com/en-us/library/ms646269(VS.85).aspx)
/// Declared in Winuser.h, include Windows.h
/// </remarks>
/// <visibility>internal</visibility>
internal struct HardwareInput
{
    /// <summary>
    /// Specifies the message generated by the input hardware. 
    /// </summary>
    /// <visibility>internal</visibility>
#pragma warning disable CS0649 // Field is never assigned to, and will always have its default value
    internal uint Msg;

    /// <summary>
    /// Specifies the low-order word of the lParam parameter for uMsg. 
    /// </summary>
    /// <visibility>internal</visibility>
    internal ushort ParamL;

    /// <summary>
    /// Specifies the high-order word of the lParam parameter for uMsg. 
    /// </summary>
    /// <visibility>internal</visibility>
    internal ushort ParamH;
#pragma warning restore CS0649
}