namespace AutoTyper.DeviceEmulator.Native;

/// <summary>
/// Contains information about a simulated message generated by an input device other than a keyboard or mouse.
/// </summary>
/// <remarks>
/// HARDWAREINPUT structure 
/// Contains information about a simulated message generated by an input device other than a keyboard 
/// or a mouse.  
/// <code>
/// C++
/// typedef struct tagHARDWAREINPUT {
///    DWORD uMsg;
///    WORD wParamL;
///    WORD wParamH;
/// } HARDWAREINPUT, *PHARDWAREINPUT
/// </code>
/// (see: http://msdn.microsoft.com/en-us/library/ms646269(VS.85).aspx)
/// Declared in Winuser.h, include Windows.h
/// </remarks>
/// <visibility>internal</visibility>
/// <revisionhistory>
/// YYYY-MM-DD  AS#####  v#.##.##.###  Change Description
/// ==========  =======  ============  ============================================================================
/// 2013-10-15  AS00122  v0.00.00.122  Initial Version
/// 2014-03-18  AS00203  v0.00.00.203  Moved to Henooh.Utility.Native Namespace
/// 2014-04-14  AS00230  v0.00.00.230  Moved to HenoohUtility as a Class Library Project (dll)
/// 2015-04-02  AS00420  v0.00.04.000  Moved to HenoohInputSimulator Project
/// 2015-11-02  AS00552  v1.00.00.003  Use the new commenting that works with HenoohDocumentationGenerator
/// 2015-11-05  AS00555  v1.00.00.006  Renamed Namespace from HenoohInputSimulator to HenoohDeviceEmulator
/// 2015-11-11  AS00556  v1.00.01.003  Modified the summary and remarks for better formatting for Documentation
/// 2016-04-04  AS00663  v1.00.03.015  Replaced revisionhistory from CR# to AS#
/// 2016-10-11  AS00746  v1.00.03.033  Renamed the class from HARDWAREINPUT, changed access modifier
/// 2016-10-19  AS00754  v1.00.03.040  Modified summary and remarks, methods, access modifiers as internal
/// 2016-10-20  AS00755  v1.00.03.041  Added visibility xml tags
/// 2018-03-26  AS01034  v1.01.02.002  Rename namespace from HenoohDeviceEmulator to Henooh.DeviceEmulator
/// </revisionhistory>
internal struct HardwareInput
{
    /// <summary>
    /// Specifies the message generated by the input hardware. 
    /// </summary>
    /// <visibility>internal</visibility>
    internal uint Msg;

    /// <summary>
    /// Specifies the low-order word of the lParam parameter for uMsg. 
    /// </summary>
    /// <visibility>internal</visibility>
    internal ushort ParamL;

    /// <summary>
    /// Specifies the high-order word of the lParam parameter for uMsg. 
    /// </summary>
    /// <visibility>internal</visibility>
    internal ushort ParamH;
}